services:
  - type: web
    name: backend
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_NAME
        value: weather_forecast
      - key: DB_USER
        value: weather_forecast
      - key: DB_PASSWORD
        value: 123
      - key: DB_PORT
        value: 3306