databases:
  - name: weather-forecast-db
    databaseName: weather_forecast
    user: weather_forecast
    password: 123
    type: mysql
    plan: standard

services:
  - name: weather-forecast-backend
    type: web
    env: php
    plan: standard
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: weather-forecast-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: weather-forecast-db
          property: databaseName
      - key: DB_USER
        fromDatabase:
          name: weather-forecast-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: weather-forecast-db
          property: password
      - key: DB_PORT
        value: "3306"
