version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_NAME=weather_forecast
      - DB_USER=weather_forecast
      - DB_PASSWORD=123
      - DB_PORT=3306

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: weather_forecast
      MYSQL_USER: weather_forecast
      MYSQL_PASSWORD: 123
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: