version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    environment:
      - DB_HOST=weather_forecast.dpg-cpv30btumphs73c4o7e0-a.singapore-postgres.render.com
      - DB_DATABASE_NAME=weather_forecast_x522
      - DB_USERNAME=weather_forecast
      - DB_PORT=5432
      - DB_PASSWORD=WwHJtD4Cy1Ipj8RBCGy0ST1DSqZUdzgn
      - DB_DIALECT=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h weather_forecast.dpg-cpv30btumphs73c4o7e0-a.singapore-postgres.render.com -p 5432 -U weather_forecast"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge